Update sonarcloud.yml

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -1,4 +1,5 @@
 name: CI
+
 permissions:
   contents: write
 
@@ -58,26 +59,27 @@ jobs:
         uses: SonarSource/sonarqube-scan-action@v4
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        continue-on-error: true  # Ensures pipeline continues even if SonarCloud fails
 
-  update-helm-chart: 
-   runs-on: ubuntu-latest
-   needs: sonarcloud
-   steps:
-    - name: Checkout Repository
-      uses: actions/checkout@v4
+  update-helm-chart:
+    runs-on: ubuntu-latest
+    needs: sonarcloud
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
 
-    - name: Configure Git
-      run: |
-        git config --global user.email "omraut0508@gmail.com"
-        git config --global user.name "om0508"
+      - name: Configure Git
+        run: |
+          git config --global user.email "omraut0508@gmail.com"
+          git config --global user.name "om0508"
 
-    - name: Update Helm Chart Tag
-      run: |
-        sed -i "s/tag: .*/tag: \"${{ github.run_id }}\"/" application-game-charts/values.yaml
+      - name: Update Helm Chart Tag
+        run: |
+          sed -i "s/tag: .*/tag: \"${{ github.run_id }}\"/" application-game-charts/values.yaml
 
-    - name: Commit and Push Changes
-      run: |
-        git add application-game-charts/values.yaml
-        git commit -m "Update tag in Helm chart" || echo "No changes to commit."
-        git pull origin main --rebase || git rebase --abort
-        git push origin main
+      - name: Commit and Push Changes
+        run: |
+          git add application-game-charts/values.yaml
+          git commit -m "Update tag in Helm chart" || echo "No changes to commit."
+          git pull --rebase origin main || git rebase --abort
+          git push origin main
